---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      proxy:
        ipv4_address: 172.24.0.14
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - {{ config_directory }}/sonarr:/config
      - /mnt/eleanor/tv:/tv
      - /mnt/eleanor/downloads/:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  proxy:
    external: true