---
version: '2.1'
services:
  code-server:
    container_name: code-server
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.22
    environment:
      PUID: 1000
      PGID: 1000
      DEFAULT_WORKSPACE: /config/project
    ports:
      - 8443:8443
    volumes:
      - '{{ config_directory }}/coder/.local:/config/'
      - '/mnt/eleanor/git/:/config/project'
      - '/home/sysadmin/.ssh/:/config/.ssh/'
    restart: unless-stopped

networks:
  proxy:
    external: true