---
- name: Franklin
  hosts: franklin
  remote_user: pi
  become: true
  tasks:
    - name: Common Configuration
      when: clean is defined
      ansible.builtin.include_tasks:
        file: linux/main.yml
    - name: Mount Configuration
      when: clean is defined
      ansible.builtin.include_tasks:
        file: mount/main.yml
    - name: Docker Configuration
      ansible.builtin.include_tasks:
        file: docker/setup/main.yml
    - name: Docker deployment
      ansible.builtin.include_tasks:
        file: docker/deploy/main.yml
      with_items:
        - "{{ services }}"