---
- name: Personal Deployment
  hosts: all
  remote_user: '{{ remote_user }}'
  become: true
  tasks:
    - name: Update OS
      apt:
        update_cache: true
        upgrade: full
    - name: Linux configuration
      when: linux is true
      include_tasks:
        file: linux/main.yml
    - name: Unbound configuration
      when: unbound is true
      include_tasks:
        file: unbound/main.yml
    - name: Setup docker
      when: docker.setup is true
      include_tasks:
        file: docker/setup/main.yml
    - name: docker deployment
      when: docker.deploy is true
      include_tasks:
        file: docker/deploy/main.yml
      with_items:
        - "{{ services }}"