---
- name: Personal Deployment
  hosts: all
  remote_user: '{{ remote_user }}'
  become: true
  tasks:
    - name: Update OS
      when: update is true
      apt:
        update_cache: true
        upgrade: full
    - name: Unbound configuration
      when: unbound is true
      include_tasks:
        file: unbound/main.yml
    - name: Linux configuration
      when: linux is true
      include_tasks:
        file: linux/main.yml
    - name: Mount configuration
      when: mount is true
      include_tasks:
        file: mount/main.yml
    - name: Setup Podman
      when: podman.setup is true
      include_tasks:
        file: podman/setup/main.yml
    - name: Podman deployment
      when: podman.deploy is true
      include_tasks:
        file: podman/deploy/main.yml
      with_items:
        - "{{ services }}"
    - name: Podman pruning
      when: podman.prune is true
      command: sudo podman system prune -a