http:
  routers:
    authelia:
      entryPoints:
        - http
      service: authelia
      rule: Host(`auth.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    authelia-https:
      entryPoints:
        - https
      service: authelia
      rule: Host(`auth.abhishekpai.co.uk`)
      middlewares:
        - authelia-auth
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
  services:
    authelia:
      loadBalancer:
        servers:
          - url: "http://192.168.1.1:9091"