http:
  routers:
    ollama:
      entryPoints:
        - http
      service: open-webui
      rule: Host(`ollama.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    ollama-https:
      entryPoints:
        - https
      service: open-webui
      rule: Host(`ollama.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
  services:
    open-webui:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:3001"