http:
  routers:
    pihole:
      entryPoints:
        - http
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    pihole-https:
      entryPoints:
        - https
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      middlewares:
        - authelia-auth
        - redirect-to-admin
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.4:80/admin"
  middlewares:
    redirect-to-admin:
      redirectregex:
        regex: ^https:\/\/([^\/]+)\/?$
        replacement: https://${1}/admin/