http:
  routers:
    pihole:
      entryPoints:
        - http
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    pihole-https:
      entryPoints:
        - https
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      middlewares:
        - authelia-auth
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.1/admin"