http:
  routers:
    portainer:
      entryPoints:
        - http
      service: portainer
      rule: Host(`portainer.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    portainer-https:
      entryPoints:
        - https
      service: portainer
      rule: Host(`portainer.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "http://192.168.1.1:9000"