http:
  routers:
    sonarr:
      entryPoints:
        - http
      service: sonarr
      rule: Host(`sonarr.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    sonarr-https:
      entryPoints:
        - https
      service: sonarr
      rule: Host(`sonarr.abhishekpai.co.uk`)
      middlewares:
        - authelia-auth
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
  services:
    sonarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:8989"