http:
  routers:
    traefik:
      entryPoints:
        - http
      service: api@internal
      rule: Host(`traefik.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    traefik-https:
      entryPoints:
        - https
      service: api@internal
      rule: Host(`traefik.abhishekpai.co.uk`)
      middlewares:
        - authelia-auth
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"