http:
  routers:
    vaultwarden:
      entryPoints:
        - http
      service: vaultwarden
      rule: Host(`vault.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    vaultwarden-https:
      entryPoints:
        - https
      service: vaultwarden
      rule: Host(`vault.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
  services:
    vaultwarden:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:81"