---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - '{{ config_directory }}/prowlarr/:/config'
    ports:
      - 9696:9696
    restart: unless-stopped
