---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      proxy:
        ipv4_address: 172.24.0.12
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - '{{ config_directory }}/prowlarr.xml:/config/config.xml:rw'
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  proxy:
    external: true