- name: Pull latest {{ item.image }}
  when: podman.pull is true
  command:
    cmd: podman pull {{ item.image }}
- name: Create {{ item.container }} configuration directory
  file:
    path: '{{ config_directory }}/{{ item.container }}'
    state: directory
    mode: 0700
    owner: root
    group: root
- name: Setup {{ item.container }} configuration
  when: item.config is defined
  include_tasks:
    file: '{{ item.container }}/main.yml'
- name: Copy {{ item.container }} docker files
  template:
    src: '{{ item.container }}/docker-compose.yml'
    dest: '{{ config_directory }}/docker-compose.yml'
- name: Stop {{ item.container }} container
  ignore_errors: true
  when: podman.stop is true
  command:
    cmd: podman stop {{ item.container }}
- name: Delete {{ item.container }} container
  ignore_errors: true
  when: podman.delete is true
  command:
    cmd: podman rm {{ item.container }}
- name: Start {{ item.container }} container
  ignore_errors: true
  command:
    cmd: 'podman-compose -f {{ config_directory }}/docker-compose.yml up -d'
- name: Copy {{ item.container }} traefik configuration
  when: item.traefik is defined
  include_tasks:
    file: traefik/deploy/main.yml
- name: Delete {{ item.container }} docker compose file
  file:
    path: '{{ config_directory }}/docker-compose.yml'
    state: absent