theme: dark
log:
  level: debug
  format: 'json'
  file_path: /config/authelia.log
identity_validation:
  reset_password:
    jwt_secret: {{ authelia_jwt_secret }}
access_control:
  default_policy: deny
  rules:
    - domain: 'pihole.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'wireguard.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'traefik.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'prowlarr.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'sonarr.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'radarr.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'deluge.abhishekpai.co.uk'
      policy: one_factor
    - domain: 'dashboard.abhishekpai.co.uk'
      policy: one_factor
session:
  name: authelia_session
  secret: {{ authelia_session_secret }}
  expiration: 1h
  inactivity: 5m
  remember_me: 1M
  cookies:
    - domain: 'abhishekpai.co.uk'
      authelia_url: 'https://auth.abhishekpai.co.uk'
      default_redirection_url: https://dashboard.abhishekpai.co.uk
regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m
storage:
  encryption_key: {{ authelia_storage_encryption_key }}
  postgres:
    address: 'tcp://172.24.0.17:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    password: {{ authelia_postgres_password }}
    timeout: '5s'
notifier:
  disable_startup_check: false
  filesystem:
    filename: '/config/notification.txt'
authentication_backend:
  refresh_interval: 5m
  password_reset:
    disable: false
    custom_url: ""
  file:
    path: /config/users.yml