---
version: "3"
services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:4.38.8
    networks:
      proxy:
        ipv4_address: 172.24.0.6
    ports:
      - 9091:9091
    volumes:
      - '{{ config_directory }}/authelia/config:/config'
    restart: unless-stopped

networks:
  proxy:
    external: true