---
- name: Common Configuration
  hosts: "*"
  tasks:
    - name: Update Raspbian
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
    - name: Turn-off and uninstall swap file
      ansible.builtin.shell:
        cmd: dphys-swapfile swapoff && dphys-swapfile uninstall
    - name: Disable swap file service
      ansible.builtin.systemd:
        name: dphys-swapfile
        enabled: false
        state: stopped
    - name: RAID md0 directory
      ansible.builtin.file:
        path: /media/md0
        state: directory
        mode: '0755'
    - name: RAID md1 directory
      ansible.builtin.file:
        path: /media/md1
        state: directory
        mode: '0755'
