- name: Install DDClient
  ansible.builtin.apt:
    name:
      - ddclient
- name: Copy ddclient configuration
  ansible.builtin.copy:
    remote_src: true
    src: /media/md1/config/ddns/ddclient.conf
    dest: /etc/ddclient.conf
- name: Start DDclient service
  ansible.builtin.systemd:
    name: ddclient
    enabled: true
    state: started