- name: Keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings/
    state: directory
    mode: 0755
    owner: pi
    group: pi
- name: Check for repository key
  ansible.builtin.file:
    state: absent
    path: '{{ item }}'
  with_items:
    - /etc/apt/keyrings/docker
    - /etc/apt/keyrings/docker.gpg
    - /etc/apt/sources.list.d/docker.list
- name: Add repository key
  ansible.builtin.get_url:
    force: true
    url: https://download.docker.com/linux/raspbian/gpg
    dest: /etc/apt/keyrings/docker
    mode: 755
- name: Dearmor key
  ansible.builtin.shell:
    cmd: gpg --dearmor /etc/apt/keyrings/docker
- name: Adding repository
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian bullseye stable
    state: present
    filename: docker
    update_cache: true
- name: Install docker packages
  ansible.builtin.apt:
    name:
      - docker
      - docker-compose
      - docker-doc
      - docker.io
      - containerd
- name: Copy docker files
  ansible.builtin.copy:
    src: ../docker/'{{ item }}'
    dest: /mnt/md1/config/docker/
  loop:
    - dockerfile.deluge
    - dockerfile.jellyfin
    - dockerfile.pihole
    - dockerfile.prowlarr
    - dockerfile.radarr
    - dockerfile.sonarr
- name: Docker compose
  ansible.builtin.command:
    cmd: docker-compose -f /mnt/md1/config/docker/{{ item }} up -d
  loop:
    - dockerfile.deluge
    - dockerfile.jellyfin
    - dockerfile.pihole
    - dockerfile.prowlarr
    - dockerfile.radarr
    - dockerfile.sonarr
- name: Delete Docker files
  ansible.builtin.file:
    path: /mnt/md1/config/docker
    state: absent
