---
- name: Franklin
  hosts: franklin
  remote_user: pi
  become: true
  tasks:
    - name: Common Configuiration
      ansible.builtin.include_tasks:
        file: common.yml
    - name: Mount Configuiration
      ansible.builtin.include_tasks:
        file: mount.yml
    - name: DDClient Configuiration
      ansible.builtin.include_tasks:
        file: ddclient.yml
    - name: Docker Configuiration
      ansible.builtin.include_tasks:
        file: docker.yml
    - name: PiVPN Configuiration
      ansible.builtin.include_tasks:
        file: pivpn.yml
