---
- name: Franklin
  hosts: franklin
  tasks:
    - name: Common Configuiration
      ansible.builtin.include_tasks:
        file: common.yml
    - name: Hardware Video Encoding
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        search_string: 'dtoverlay='
        line: 'dtoverlay/=/rpivid-v4l2'
    - name: Fan controls GPIO Configuration
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        search_string: 'dtoverlay='
        line: 'dtoverlay/=/gpio-fan,gpiopin/=/3,temp/=/60000'
    - name: Copy fan controls script
      ansible.builtin.copy:
        src: ../fancontrol/fancontrol.py
        dest: /home/pi/fancontrol/
        owner: pi
        group: pi
        mode: '0755'
    - name: Copy fan controls service
      ansible.builtin.copy:
        src: ../fancontrol/fancontrol.service
        dest: /lib/systemd/system/fancontrol.service
        owner: pi
        group: pi
        mode: 0755
    - name: Load, enable & start fancontrol service
      ansible.builtin.systemd:
        daemon_reload: true
        name: fancontrol
        enabled: true
        state: started
    - name: Install NFS Client
      ansible.builtin.apt:
        name:
          - nfs-common
    - name: NFS Mount md0 RAID from Eleanor
      ansible.posix.mount:
        src: eleanor:/media/md0
        path: /media/md0
        state: mounted
        fstype: nfs
    - name: NFS Mount md1 RAID from Eleanor
      ansible.posix.mount:
        src: eleanor:/media/md1
        path: /media/md1
        state: mounted
        fstype: nfs
    - name: Install Deluge Daemon and Web Client
      ansible.builtin.apt:
        name:
          - deluged
          - deluge-web
    - name: Copy Custom Deluge Service
      ansible.builtin.copy:
        src: ../deluged/deluged.service
        dest: /lib/systemd/system/deluge.service
        owner: pi
        group: pi
        mode: 0755
    - name: Deluge Web Client Configuration
      ansible.builtin.lineinfile:
        path: /home/pi/.config/deluge/web.conf
        line: '"default_daemon": "127.0.0.1:58846"'
    - name: Copy Deluged Service Configuration
      ansible.builtin.copy:
        src: ../deluged/deluge-config
        dest: /etc/defaults/deluged/
        owner: pi
        group: pi
        mode: 0755
    - name: Copy Deluged Application Configuration
      ansible.builtin.copy:
        src: ../deluged/core.conf
        dest: /home/pi/.config/deluge/
        owner: pi
        group: pi
        mode: 0755
    - name: Load, enable & start Deluge service
      ansible.builtin.systemd:
        daemon_reload: true
        name: deluge
        enabled: true
        state: started
    - name: Copy DuckDNS script
      ansible.builtin.copy:
        src: ../duckdns/duck.sh
        dest: /home/pi/duckdns/
        owner: pi
        group: pi
        mode: 0755
    - name: DuckDNS Cron
      ansible.builtin.cron:
        name: DuckDNS
        minute: "*/5"
        user: root
        job: "~/duckdns/duck.sh >/dev/null 2>&1"
    - name: Cron Service
      ansible.builtin.systemd:
        name: cron
        enabled: true
        state: started
