---
- name: Franklin
  hosts: franklin
  remote_user: pi
  become: true
  tasks:
    - name: Common Configuiration
      ansible.builtin.include_tasks:
        file: common.yml
    - name: Install NFS Client
      ansible.builtin.apt:
        name:
          - nfs-common
    - name: NFS Mount md0 RAID from Eleanor
      ansible.posix.mount:
        src: eleanor:/media/md0
        path: /media/md0
        state: mounted
        fstype: nfs
    - name: NFS Mount md1 RAID from Eleanor
      ansible.posix.mount:
        src: eleanor:/media/md1
        path: /media/md1
        state: mounted
        fstype: nfs
    - name: Install DDClient
      ansible.builtin.apt:
        name:
          - ddclient
    - name: Copy ddclient configuration
      ansible.builtin.copy:
        remote_src: true
        src: /media/md1/config/ddns/ddclient.conf
        dest: /etc/ddclient.conf
    - name: Start DDclient service
      ansible.builtin.systemd:
        name: ddclient
        enabled: true
        state: started
    - name: Install docker auxiliary packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - curl
          - ca-certificates
    - name: Add repository key
      ansible.builtin.get_url:
        force: true
        url: https://download.docker.com/linux/raspbian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: 755
    - name: Adding repository
      ansible.builtin.apt_repository:
        repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/raspbian bullseye stable
        state: present
        filename: docker
        update_cache: true
    - name: Install docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
    - name: Install unbound
      ansible.builtin.apt:
        name:
          - unbound
    - name: Copy root.hints
      ansible.builtin.copy:
        src: ../pi-hole/root.hints
        dest: /var/lib/unbound/
    - name: Copy pihole configuration
      ansible.builtin.copy:
        src: ../pi-hole/pi-hole.conf
        dest: /etc/unbound/unbound.conf.d/    
    - name: Restart unbound service
      ansible.builtin.systemd:
        name: unbound
        state: restarted
    - name: Copy docker files
      ansible.builtin.copy:
        src: '{{item}}'
        dest: /media/md1/config/docker/
      loop:
        - ../docker/dockerfile.deluge
        - ../docker/dockerfile.jellyfin
        - ../docker/dockerfile.pihole
        - ../docker/dockerfile.prowlarr
        - ../docker/dockerfile.radarr
        - ../docker/dockerfile.sonarr
    - name: Docker compose
      ansible.builtin.command:
        cmd: docker compose -f {{item}} up -d
      loop:
        - /media/md1/config/docker/dockerfile.deluge
        - /media/md1/config/docker/dockerfile.jellyfin
        - /media/md1/config/docker/dockerfile.pihole
        - /media/md1/config/docker/dockerfile.prowlarr
        - /media/md1/config/docker/dockerfile.radarr
        - /media/md1/config/docker/dockerfile.sonarr
    - name: Delete Docker files
      ansible.builtin.file:
        path: /media/md1/config/docker
        state: absent
    - name: Download piVPN script
      ansible.builtin.get_url:
        url: https://install.pivpn.io
        dest: /media/md1/config/pivpn/install.sh
    - name: Enable execute permission
      ansible.builtin.file:
        path: /media/md1/config/pivpn/install.sh
        owner: pi
        group: pi
        mode: 0755
    - name: Execute piVPN setup
      ansible.builtin.command:
        cmd: bash /media/md1/config/pivpn/install.sh --unattended /media/md1/config/pivpn/setupVars.conf
    - name: Delete piVPN script
      ansible.builtin.file:
        path: /media/md1/config/pivpn/install.sh
        state: absent
