---
version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    networks:
      proxy:
        ipv4_address: 172.24.0.8
    ports:
      - 82:80
    volumes:
      - '{{ home_directory }}/docker_config/vaultwarden:/data'
    environment:
      - ADMIN_TOKEN={{ vaultwarden_admin_password }}
    restart: unless-stopped

networks:
  proxy:
    external: true