---
version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    ports:
      - 82:80
    volumes:
      - /home/pi/docker_config/vaultwarden:/data
    environment:
      - ADMIN_TOKEN={{ vaultwarden_admin_password }}
    restart: unless-stopped