---
version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.8
    ports:
      - 81:80
    volumes:
      - '{{ config_directory }}/vaultwarden.json:/data/config.json'
    environment:
      ADMIN_TOKEN: {{ vaultwarden_admin_password }}
      I_REALLY_WANT_VOLATILE_STORAGE: 'true'
      DATABASE_URL: postgresql://vaultwarden:{{ vaultwarden_admin_password }}@172.24.0.17:5432/vaultwarden
    restart: unless-stopped

networks:
  proxy:
    external: true