---
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      proxy:
        ipv4_address: 172.24.0.2
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - '{{ config_directory }}/pihole/etc-pihole:/etc/pihole'
      - '{{ config_directory }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  proxy:
    external: true