- name: Install unbound
  ansible.builtin.apt:
    name:
      - unbound
- name: Copy pihole configuration
  ansible.builtin.copy:
    src: ../pi-hole/pi-hole.conf
    dest: /etc/unbound/unbound.conf.d/    
- name: Restart unbound service
  ansible.builtin.systemd:
    name: unbound
    state: start
- name: PiVPN config folder
  ansible.builtin.file:
    path: /home/pi/pivpn/
    state: directory
- name: Download piVPN script
  ansible.builtin.get_url:
    url: https://install.pivpn.io
    dest: /home/pi/pivpn/install.sh
- name: PiVPN configuration
  ansible.builtin.copy:
    src: setupVars.conf
    dest: /home/pi/pivpn/setupVars.conf
- name: Enable execute permission
  ansible.builtin.file:
    path: /home/pi/docker/pivpn/install.sh
    owner: pi
    group: pi
    mode: 0755
- name: Execute piVPN setup
  ansible.builtin.command:
    cmd: bash /home/pi/pivpn/install.sh --unattended /home/pi/pivpn/setupVars.conf
- name: Delete piVPN script
  ansible.builtin.file:
    path: /home/pi/pivpn/
    state: absent