- name: Install mdadm
  ansible.builtin.apt:
    name:
      - mdadm
- name: Copy mdadm configuration
  ansible.builtin.copy:
    src: mdadm.conf
    dest: /etc/mdadm/
- name: Assemble RAID
  ansible.builtin.command:
    cmd: sudo mdadm --assemble --scan --verbose {{ item }}
  loop:
      - /dev/md0 /dev/sda /dev/sdb
      - /dev/md1 /dev/sdc /dev/sdd
- name: Copy mdadm script
  ansible.builtin.copy:
    src: mdadm-readwrite.sh
    dest: /home/pi/
- name: Copy mdadm script
  ansible.builtin.copy:
    src: mdadm-readwrite.service
    dest: /etc/systemd/system/
- name: Configuration mdadm service
  ansible.builtin.service:
    name: mdadm-readwrite.service
    enabled: true
    state: reloaded
