http:
  routers:
    nextcloud:
      entryPoints:
        - http
      service: nextcloud
      rule: Host(`cloud.abhishekpai.co.uk`)
      middlewares:
        - nextcloud-https-redirect
    nextcloud-https:
      entryPoints:
        - https
      service: nextcloud
      rule: Host(`cloud.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
    pihole:
      entryPoints:
        - http
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      middlewares:
        - pihole-https-redirect
    pihole-https:
      entryPoints:
        - https
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
  middlewares:
    nextcloud-https-redirect:
      redirectscheme:
        scheme: https
    pihole-https-redirect:
      redirectscheme:
        scheme: https
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "https://192.168.1.2"
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.1/admin"