http:
  routers:
    nextcloud:
      entryPoints:
        - http
      service: nextcloud
      rule: Host(`cloud.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    nextcloud-https:
      entryPoints:
        - https
      service: nextcloud
      rule: Host(`cloud.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
    pihole:
      entryPoints:
        - http
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    pihole-https:
      entryPoints:
        - https
      service: pihole
      rule: Host(`pihole.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
    sonarr:
      entryPoints:
        - http
      service: sonarr
      rule: Host(`sonarr.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    sonarr-https:
      entryPoints:
        - https
      service: sonarr
      rule: Host(`sonarr.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
    radarr:
      entryPoints:
        - http
      service: radarr
      rule: Host(`radarr.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    radarr-https:
      entryPoints:
        - https
      service: radarr
      rule: Host(`radarr.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
    prowlarr:
      entryPoints:
        - http
      service: prowlarr
      rule: Host(`prowlarr.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    prowlarr-https:
      entryPoints:
        - https
      service: prowlarr
      rule: Host(`prowlarr.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
    deluge:
      entryPoints:
        - http
      service: sonarr
      rule: Host(`deluge.abhishekpai.co.uk`)
      middlewares:
        - https-redirect
    deluge-https:
      entryPoints:
        - https
      service: deluge
      rule: Host(`deluge.abhishekpai.co.uk`)
      tls:
        certResolver: cloudflare
        domains:
          - main: abhishekpai.co.uk
            sans:
              - "*.abhishekpai.co.uk"
          - main: abhishekpai.com
            sans:
              - "*.abhishekpai.com"
  middlewares:
    https-redirect:
      redirectscheme:
        scheme: https
        permanent: true
  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "https://192.168.1.2"
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.1/admin"
    sonarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:8989"
    radarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:7878"
    prowlarr:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:9696"
    deluge:
      loadBalancer:
        servers:
          - url: "http://192.168.1.2:8112"