---
version: "3.3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/pi/docker_config/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /home/pi/docker_config/traefik/acme.json:/etc/traefik/acme.json
      - /home/pi/docker_config/traefik/log/:/var/log/traefik/