---
version: "3.3"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    networks:
      proxy:
        ipv4_address: 172.24.0.4
    ports:
      - 8080:80
      - 443:443
      - 8000:8080
    environment:
      - CF_API_EMAIL=abpai94@gmail.com
      - CF_API_KEY={{ cloudflare_global_api_key }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - '{{ home_directory }}/docker_config/traefik/config/:/etc/traefik/'
      - '{{ home_directory }}/docker_config/traefik/log/:/var/log/traefik/'
    restart: unless-stopped

networks:
  proxy:
    external: true