---
version: "3.3"
services:
  traefik:
    container_name: traefik
    image: docker.io/traefik:v3.0.0
    networks:
      proxy:
        ipv4_address: 172.24.0.4
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=abpai94@gmail.com
      - CF_ZONE_API_TOKEN={{ cloudflare.zone_api_token }}
      - CF_DNS_API_TOKEN={{ cloudflare.dns_api_token }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - '{{ config_directory }}/traefik/config/:/etc/traefik/'
      - '{{ config_directory }}/traefik/log/:/var/log/traefik/'
    restart: unless-stopped

networks:
  proxy:
    external: true