---
version: "3.3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 81:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=abpai94@gmail.com
      - CF_API_KEY={{ cloudflare_global_api_key }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/pi/docker_config/traefik/config/:/etc/traefik/
      - /home/pi/docker_config/traefik/log/:/var/log/traefik/
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.abhishekpai.co.uk`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`traefik.abhishekpai.co.uk`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$s.LL3vc/$$fq06HiuW.F.hdID56Zfgb/
      - traefik.http.middlewares.traefik-auth.basicauth.removeheader=true
      - traefik.http.middlewares.traefik-sslheaders.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik-https.middlewares=traefik-auth
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certresolver=cloudflare
      - traefik.http.routers.traefik-https.tls.domains[0].main=abhishekpai.co.uk
      - traefik.http.routers.traefik-https.tls.domains[0].sans=*.abhishekpai.co.uk
      - traefik.http.routers.traefik-https.service=api@internal