- name: Create folders
  file:
    path: '{{ config_directory }}/traefik/config'
    state: directory
- name: Create folders
  file:
    path: '{{ config_directory }}/traefik/config/proxy'
    state: directory
- name: Copy traefik configuration file
  template:
    src: '{{ file }}'
    dest: '{{ config_directory }}/traefik/config/{{ file }}'
  loop:
    - traefik.yml
    - proxy/common.yml
    - proxy/deluge.yml
    - proxy/jellyfin.yml
    - proxy/prowlarr.yml
    - proxy/radarr.yml
    - proxy/sonarr.yml
    - proxy/nextcloud.yml
  loop_control:
    loop_var: file