global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  http:
    address: :80
  https:
    address: :443
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "abhishekpai.co.uk"
            sans: 
             - "*.abhishekpai.co.uk"
          - main: "abhishekpai.com"
            sans: 
             - "*.abhishekpai.com"


providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  cloudflare:
    acme:
      email: abpai94@gmail.com
      storage: /etc/traefik/acme.json
      tlsChallenge:
        {}
      httpChallenge:
        entryPoint: https
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: "0"