global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: "/var/log/traefik/access.log"

api:
  insecure: true
  dashboard: true
  debug: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :81
  https:
    address: :443
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "abhishekpai.co.uk"
            sans: 
             - "*.abhishekpai.co.uk"

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    watch: true
    directory: /etc/traefik/proxy/

certificatesResolvers:
  cloudflare:
    acme:
      email: abpai94@gmail.com
      storage: /etc/traefik/acme.json
      tlsChallenge:
        {}
      httpChallenge:
        entryPoint: https
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: "0"