global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: DEBUG
  filePath: /var/log/traefik/traefik.log

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: :80
  https:
    address: :443

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  cloudflare:
    acme:
      email: abpai94@gmail.com
      storage: /etc/traefik/acme.json
      tlschallenge: true