---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - /media/md1/config/jellyfin/:/config
      - /media/md1/tv:/data/tvshows
      - /media/md1/movies:/data/movies
    ports:
      - 8096:8096      
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped