---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /media/md1/config/sonarr:/config
      - /media/md1/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
