---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    volumes:
      - /media/md1/config/radarr/:/config
      - /media/md1/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped