---
version: "3"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    network_mode: host
    ports:
      - 80:80
    volumes:
      - /home/pi/docker/vaultwarden:/data