---
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1001
    volumes:
      - /home/pi/docker/pihole/etc/pihole:/etc/pihole
      - /home/pi/docker/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped