---
version: "2.1"
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /mnt/md1/config/unbound/:/opt/unbound/etc/unbound/
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    restart: unless-stopped
