- name: Download Docker script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /home/pi/installDocker.sh
- name: Enable Docker script execute permission
  ansible.builtin.file:
    path: /home/pi/installDocker.sh
    owner: pi
    group: pi
    mode: 0755
- name: Execute Docker script
  ignore_errors: true
  ansible.builtin.command:
    cmd: bash /home/pi/installDocker.sh
- name: Delete docker installation script
  ansible.builtin.file:
    path: /home/pi/installDocker.sh
    state: absent
- name: Docker Compose
  ansible.builtin.apt:
    name: docker-compose
- name: Copy Cloudflare API Key
  ansible.builtin.copy:
    src: certbot/cloudflare.ini
    dest: ~/docker/certbot/cloudflare.ini
- name: Copy docker files
  ansible.builtin.copy:
    src: ../docker/{{ item }}
    dest: /home/pi/docker_files/
  loop:
    - dockerfile.deluge
    - dockerfile.jellyfin
    - dockerfile.prowlarr
    - dockerfile.radarr
    - dockerfile.sonarr
    - dockerfile.certbot
- name: Docker compose
  ansible.builtin.command:
    cmd: docker-compose -f /home/pi/docker_files/{{ item }} up -d
  loop:
    - dockerfile.deluge
    - dockerfile.jellyfin
    - dockerfile.prowlarr
    - dockerfile.radarr
    - dockerfile.sonarr
    - dockerfile.certbot
- name: Delete Docker files
  ansible.builtin.file:
    path: /home/pi/docker_files/
    state: absent
