- name: Download Docker script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /home/pi/installDocker.sh
    mode: 0755
    owner: pi
    group: pi
- name: Execute Docker script
  ignore_errors: true
  ansible.builtin.command:
    cmd: bash /home/pi/installDocker.sh
- name: Delete docker installation script
  ansible.builtin.file:
    path: /home/pi/installDocker.sh
    state: absent
- name: Docker Compose
  ansible.builtin.apt:
    name: docker-compose
- name: Copy Original Config
  ansible.builtin.copy:
    src: /mnt/md1/docker_config/
    dest: /home/pi/docker_config/
    mode: 0755
    owner: pi
    group: pi
    remote_src: true
- name: Crontab backup
  ansible.builtin.cron:
    name: "Docker configuration backup"
    minute: "0"
    hour: "2"
    user: root
    job: "rsync -a --delete-after /home/pi/docker_config/ /mnt/md1/docker_config/"
- name: Copy Cloudflare API Key
  ansible.builtin.copy:
    src: certbot/cloudflare.ini
    dest: ~/.secrets/cloudflare.ini
- name: Stop containers
  ignore_errors: true
  ansible.builtin.command:
    cmd: sudo docker stop {{ item }}
  loop:
    - deluge
    - jellyfin
    - prowlarr
    - radarr
    - sonarr
    - certbot
    - traefik
- name: Remove containers
  ignore_errors: true
  ansible.builtin.command:
    cmd: sudo docker rm {{ item }}
  loop:
    - deluge
    - jellyfin
    - prowlarr
    - radarr
    - sonarr
    - certbot
    - traefik
- name: Copy docker files
  ignore_errors: true
  ansible.builtin.copy:
    src: ../docker/{{ item }}/docker-compose.yml
    dest: /home/pi/docker_files/{{ item }}/
  loop:
    - deluge
    - jellyfin
    - prowlarr
    - radarr
    - sonarr
    - certbot
    - traefik
- name: Start containers
  ignore_errors: true
  ansible.builtin.command:
    cmd: docker-compose -f /home/pi/docker_files/{{ item }}/docker-compose.yml up -d
  loop:
    - deluge
    - jellyfin
    - prowlarr
    - radarr
    - sonarr
    - certbot
    - traefik
- name: Delete Docker files
  ansible.builtin.file:
    path: /home/pi/docker_files/
    state: absent
