---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    networks:
      proxy:
        ipv4_address: 172.24.0.16
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - '{{ config_directory }}/nextcloud/config/:/config'
      - /mnt/eleanor/cloud/:/data
      - /mnt/eleanor/photos:/photos
    ports:
      - 83:443
    restart: unless-stopped

networks:
  proxy:
    external: true