---
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - '{{ config_directory }}/nextcloud/config/:/config'
      - /mnt/eleanor/cloud/:/data
    ports:
      - 444:443
    restart: unless-stopped