---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - '{{ home_directory }}/docker_config/radarr/:/config'
      - /mnt/md1/movies:/movies
      - /mnt/md1/downloads/:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped