---
version: "2.1"
services:
  radarr:
    container_name: radarr
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.13
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - '{{ config_directory }}/radarr.xml:/config/config.xml:rw'
      - /mnt/eleanor/movies:/movies
      - /mnt/eleanor/downloads/:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  proxy:
    external: true