---
version: '3.9'
services:
  pgadmin:
    container_name: pgadmin
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.18
    ports:
      - 84:80/tcp
    environment:
      PGADMIN_DEFAULT_EMAIL: abpai94@gmail.com
      PGADMIN_DEFAULT_PASSWORD: {{ postgres_password }}
    volumes:
      - '{{ config_directory }}/pgadmin:/var/lib/pgadmin'
    restart: unless-stopped

networks:
  proxy:
    external: true