---
version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 3000:3000
    volumes:
      - /home/pi/docker_config/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /media/md0:/mnt/md0
      - /media/md1:/mnt/md1
    restart: unless-stopped