- Network:
  - Router:
      href: http://192.168.1.254/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/freebox-revolution.png
  - PiHole:
      href: http://192.168.1.1/admin/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png
      container: pihole
  - Wireguard:
      href: http://192.168.1.1:51821/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/wireguard.png
      container: wireguard
- Aggregatarrs:
  - Sonarr:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png
      href: http://192.168.1.2:8989/
      widget:
        type: sonarr
        url: http://192.168.1.2:8989/
        key: {{ sonarr_api_key }}
  - Radarr:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png
      href: http://192.168.1.2:7878/
      widget:
        type: radarr
        url: http://192.168.1.2:7878/
        key: {{ radarr_api_key }}
  - Prowlarr:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png
      href: http://192.168.1.2:9696/
      widget:
        type: prowlarr
        url: http://192.168.1.2:9696/
        key: {{ prowlarr_api_key }}
  - Deluge:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/deluge.png
      href: http://192.168.1.2:8112/
- Media:
  - Jellyfin:
      href: http://192.168.1.2:8096/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png
  - Nextcloud:
      href: https://192.168.1.2/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png