- Downloaders:  
  - Prowlarr:
      href: http://192.168.1.2:9696/
      siteMonitor: http://192.168.1.2:9696/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png
      widget:
        type: prowlarr
        url: http://192.168.1.2:9696
        key: {{ prowlarr_api_key }}
  - Sonarr:
      href: http://192.168.1.2:8989/
      siteMonitor: http://192.168.1.2:8989/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png
      widget:
        type: sonarr
        url: http://192.168.1.2:8989
        key: {{ sonarr_api_key }}
  - Radarr:
      href: http://192.168.1.2:7878/
      siteMonitor: http://192.168.1.2:7878/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png
      widget:
        type: radarr
        url: http://192.168.1.2:7878
        key: {{ radarr_api_key }}
  - Deluge:
      href: http://192.168.1.2:8112/
      siteMonitor: http://192.168.1.2:8112/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/deluge.png
      widget:
        type: deluge
        url: http://192.168.1.2:8112
        password: {{ deluge_password }}
- Services:
  - PiHole:
      href: http://192.168.1.1/admin/
      siteMonitor: http://192.168.1.1/admin/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png
      container: pihole
      widget:
        type: pihole
        url: http://192.168.1.1
        key: {{ pihole_api_key }}
  - Router:
      href: http://192.168.1.254/
      siteMonitor: http://192.168.1.254/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/freebox-revolution.png
  - Wireguard:
      href: http://192.168.1.1:51821/
      siteMonitor: http://192.168.1.1:51821/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/wireguard.png
      container: wireguard
  - Jellyfin:
      href: http://192.168.1.2:8096/
      siteMonitor: http://192.168.1.2:8096/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png
  - Nextcloud:
      href: https://192.168.1.2/
      siteMonitor: http://192.168.1.2/
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
