---
version: "3"

services:
  wg-easy:
    environment:
      - WG_HOST=abhishekpai.co.uk
      - WG_DEFAULT_DNS=192.168.1.2
      - WG_DEFAULT_ADDRESS=10.252.1.x
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - /home/pi/docker_config/wireguard/:/etc/wireguard/
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1