- name: Download docker script
  get_url:
    url: https://get.docker.com
    dest: '{{ config_directory }}/installDocker.sh'
    mode: 0755
    owner: '{{ owner }}'
    group: '{{ group }}'
- name: Execute docker script
  command:
    cmd: bash '{{ config_directory }}/installDocker.sh'
- name: Delete docker installation script
  file:
    path: '{{ config_directory }}/installDocker.sh'
    state: absent
- name: Install docker Compose
  apt:
    name: docker-compose
- name: Docker login
  ignore_errors: true
  command:
    cmd: 'sudo docker login -u abpai94 --password {{ docker_token }}'
# - name: Added dockerd remote access configuration
#   when: inventory_hostname == 'eleanor'
#   replace:
#     path: /etc/systemd/system/multi-user.target.wants/docker.service
#     regexp: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
#     replace: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://192.168.1.2:2375
# - name: Restart docker systemd service
#   when: inventory_hostname == 'eleanor'
#   systemd_service:
#     name: docker
#     state: restarted
#     daemon_reload: true
# - name: Create docker_config folder
#   file:
#     path: '{{ config_directory }}/docker_config'
#     state: directory
#     mode: 0755
#     owner: '{{ owner }}'
#     group: '{{ group }}'
- name: Docker network command
  ignore_errors: true
  command: docker network create --driver=bridge --subnet=172.24.0.0/16 proxy --attachable=true