- name: Copy traefik configuration file for {{ item.container }}
  template:
    src: "../../traefik/proxy/{{ item.container }}.yml"
    dest: '{{ config_directory }}/traefik/config/proxy/{{ item.container }}.yml'