---
version: "2.1"
services:
  cloudflare:
    container_name: cloudflare
    image: cloudflare/cloudflared:latest 
    networks:
      proxy:
        ipv4_address: 172.24.0.11
    command:
      - tunnel run
    environment:
      - TUNNEL_TOKEN={{ cloudflare_tunnel_api_key }}
    restart: unless-stopped

networks:
  proxy:
    external: true