---
version: "2.1"
services:
  deluge:
    container_name: deluge
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.11
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=info
    volumes:
      - '{{ config_directory }}/deluge/config:/config'
      - /mnt/eleanor/downloads/:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

networks:
  proxy:
    external: true