---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - JELLYFIN_PublishedServerUrl=https://jellyfin.abhishekpai.co.uk
    volumes:
      - '{{ config_directory }}/jellyfin/:/config'
      - /mnt/eleanor/tv:/data/tvshows
      - /mnt/eleanor/movies:/data/movies
    # devices:
    #   - /dev/video10:/dev/video10
    #   - /dev/video11:/dev/video11
    #   - /dev/video19:/dev/video19
    ports:
      - 8096:8096
    restart: unless-stopped