---
version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks:
      proxy:
        ipv4_address: 172.24.0.7
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '{{ config_directory }}/portainer:/data'
    restart: unless-stopped

networks:
  proxy:
    external: true