---
version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/docker_config/portainer:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.routers.portainer.rule=Host(`portainer.abhishekpai.co.uk`)
      - traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.portainer.middlewares=portainer-https-redirect
      - traefik.http.routers.portainer-https.entrypoints=https
      - traefik.http.routers.portainer-https.rule=Host(`portainer.abhishekpai.co.uk`)
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.tls.certresolver=cloudflare
      - traefik.http.routers.portainer-https.tls.domains[0].main=abhishekpai.co.uk
      - traefik.http.routers.portainer-https.tls.domains[0].sans=*.abhishekpai.co.uk
      - traefik.http.services.portainer.loadBalancer.server.port=9000