---
version: '3'
services:
  ollama:
    container_name: ollama
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.19
    ports:
      - 11434:11434
    volumes:
      - '/mnt/eleanor/llms:/root/.ollama'
    restart: unless-stopped

networks:
  proxy:
    external: true