- name: Pull latest {{ item.image }}
  when: docker.pull is true
  command:
    cmd: sudo docker pull {{ item.image }}
- name: Copy original config {{ item.container }}
  when: docker.old_config is true
  become: false
  copy:
    src: /mnt/md0/docker_config/{{ item.container }}/
    dest: '{{ home_directory }}/docker_config/{{ item.container }}/'
    mode: 0755
    owner: '{{ owner }}'
    group: '{{ group }}'
    remote_src: true
- name: Setup {{ item.container }} configuration
  when: item.config is defined
  include_tasks:
    file: '{{ item.container }}/main.yml'
- name: Copy {{ item.container }} docker files
  template:
    src: '{{ item.container }}/docker-compose.yml'
    dest: '{{ home_directory }}/docker-compose.yml'
- name: Stop {{ item.container }} container
  when: docker.stop is true
  command:
    cmd: sudo docker stop {{ item.container }}
- name: Delete {{ item.container }} container
  when: docker.delete is true
  command:
    cmd: sudo docker rm {{ item.container }}
- name: Start {{ item.container }} container
  command:
    cmd: 'docker-compose -f {{ home_directory }}/docker-compose.yml up -d'
- name: Copy {{ item.container }} traefik configuration
  when: item.traefik is defined
  include_tasks:
    file: traefik/deploy/main.yml
- name: Delete {{ item.container }} docker compose file
  file:
    path: '{{ home_directory }}/docker-compose.yml'
    state: absent