---
version: "2.1"
services:
  ddclient:
    container_name: ddclient
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/.secrets/ddclient/:/config
    restart: unless-stopped

networks:
  proxy:
    external: true