- name: Install DDClient
  ansible.builtin.apt:
    name:
      - ddclient
- name: Copy ddclient configuration
  ansible.builtin.copy:
    src: ddclient.conf
    dest: /etc/ddclient.conf
    mode: 0660
    owner: root
    group: root
- name: Start DDclient service
  ansible.builtin.systemd:
    name: ddclient
    enabled: true
    state: started
