- name: Adding hostnames
  when: clean is defined
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      192.168.1.2     franklin
      192.168.1.3     eleanor
- name: Update Raspbian
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
- name: Restart Raspbian
  when: clean is defined
  ansible.builtin.reboot:
    reboot_timeout: 3000
- name: Update and Upgrade Cron job
  when: clean is defined
  ansible.builtin.cron:
    name: Update and Upgrade OS
    minute: 0
    hour: 2
    job: sudo apt-get update && sudo apt-get upgrade -y
- name: Turn-off swap file
  when: clean is defined
  ansible.builtin.shell:
    cmd: dphys-swapfile swapoff
- name: Uninstall swap file
  when: clean is defined
  ansible.builtin.shell:
    cmd: dphys-swapfile uninstall
- name: Disable swap file service
  when: clean is defined
  ansible.builtin.systemd:
    name: dphys-swapfile
    enabled: false
    state: stopped
- name: RAID md0 directory
  when: clean is defined
  ansible.builtin.file:
    path: /media/md0
    state: directory
    mode: 0755
    owner: pi
    group: pi
- name: RAID md1 directory
  when: clean is defined
  ansible.builtin.file:
    path: /media/md1
    state: directory
    mode: 0755
    owner: pi
    group: pi
- name: Symbolic links for md0
  when: clean is defined
  ansible.builtin.file:
    src: /media/md0
    dest: /mnt/md0
    state: link
    owner: pi
    group: pi
- name: Symbolic links for md1
  when: clean is defined
  ansible.builtin.file:
    src: /media/md1
    dest: /mnt/md1
    state: link
    owner: pi
    group: pi
- name: NFS Server Installation
  when: clean is defined
  ansible.builtin.apt:
    name: nfs-kernel-server
    update_cache: true
- name: NFS exports
  when: clean is defined
  ansible.builtin.blockinfile:
    path: /etc/exports
    block: |
      /media/md0      *(rw,sync,no_subtree_check)
      /media/md1      *(rw,sync,no_subtree_check)
- name: Export NFS Server
  when: clean is defined
  ansible.builtin.shell:
    cmd: exportfs -a
