version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    networks:
      proxy:
        ipv4_address: 172.24.0.17
    shm_size: 128mb
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: {{ postgres_password }}
    volumes:
      - '{{ config_directory }}/postgres:/var/lib/postgresql/data'
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: docker.io/dpage/pgadmin4:8.6
    networks:
      proxy:
        ipv4_address: 172.24.0.18
    ports:
      - 84:80/tcp
    environment:
      PGADMIN_DEFAULT_EMAIL: abpai94@gmail.com
      PGADMIN_DEFAULT_PASSWORD: {{ postgres_password }}
    volumes:
      - '{{ config_directory }}/pgadmin:/var/lib/pgadmin'
    restart: unless-stopped

networks:
  proxy:
    external: true