---
version: '3.9'
services:
  postgres:
    container_name: postgres
    image: '{{ item.image }}'
    networks:
      proxy:
        ipv4_address: 172.24.0.17
    shm_size: 128mb
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: {{ postgres_password }}
    volumes:
      - '{{ config_directory }}/postgres:/var/lib/postgresql/data'
    restart: unless-stopped

networks:
  proxy:
    external: true