---
version: "3"
services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    networks:
      proxy:
        ipv4_address: 172.24.0.3
    environment:
      - WG_HOST=abhishekpai.co.uk
      - WG_DEFAULT_DNS=192.168.1.2
      - WG_DEFAULT_ADDRESS=10.252.1.x
    volumes:
      - '{{ config_directory }}/wireguard/:/etc/wireguard/'
    ports:
      - "16383:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  proxy:
    external: true