---
version: "3"
services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy:latest
    environment:
      - WG_HOST=abhishekpai.co.uk
      - WG_DEFAULT_DNS=192.168.1.1
      - WG_DEFAULT_ADDRESS=10.252.1.x
      - PASSWORD={{ wireguard_password }}
    volumes:
      - /home/pi/docker_config/wireguard/:/etc/wireguard/
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.entrypoints=http
      - traefik.http.routers.wireguard.rule=Host(`wireguard.abhishekpai.co.uk`)
      - traefik.http.middlewares.wireguard-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.wireguard.middlewares=wireguard-https-redirect
      - traefik.http.routers.wireguard-https.entrypoints=https
      - traefik.http.routers.wireguard-https.rule=Host(`wireguard.abhishekpai.co.uk`)
      - traefik.http.routers.wireguard-https.tls=true
      - traefik.http.routers.wireguard-https.tls.certresolver=cloudflare
      - traefik.http.routers.wireguard-https.tls.domains[0].main=abhishekpai.co.uk
      - traefik.http.routers.wireguard-https.tls.domains[0].sans=*.abhishekpai.co.uk
      - traefik.http.services.wireguard.loadBalancer.server.port=51821